version: "3.9"

services:
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ${DATA_PATH}:/var/lib/pgadmin
