---
nginx_proxy_manager_state: present
nginx_proxy_manager_project_name: npm
nginx_proxy_manager_data_path: "{{ base_deploy_path }}/npm"

nginx_proxy_manager_compose_defaults:
  project_src: "{{ nginx_proxy_manager_data_path }}"
  state: "{{ 'present' if nginx_proxy_manager_state == 'present' else 'absent' }}"
  project_name: "{{ nginx_proxy_manager_project_name }}"
  pull: true
  recreate: smart
  remove_orphans: true
  build: false

nginx_proxy_manager_compose_overrides: {}
nginx_proxy_manager_compose: "{{ nginx_proxy_manager_compose_defaults | combine(nginx_proxy_manager_compose_overrides, recursive=True) }}"
