---
- name: Ensure pgAdmin data directory exists
  ansible.builtin.file:
    path: "{{ pgadmin_data_path }}"
    state: directory
    mode: "0750"
  when: pgadmin_compose.state != 'absent'

- name: Deploy pgAdmin compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ pgadmin_data_path }}/docker-compose.yml"
    mode: "0644"
  when: pgadmin_compose.state != 'absent'

- name: Reconcile pgAdmin compose project
  community.docker.docker_compose: "{{ pgadmin_compose }}"
  vars:
    ansible_python_interpreter: "{{ hostvars[inventory_hostname].docker_python_interpreter | default(ansible_facts.python.executable | default('/usr/bin/python3')) }}"
  when: pgadmin_compose.state in ['present', 'absent']

- name: Remove pgAdmin directory when absent
  ansible.builtin.file:
    path: "{{ pgadmin_data_path }}"
    state: absent
  when: pgadmin_compose.state == 'absent'
