---
- name: Prepare base system for homelab services
  hosts: home_lab
  become: true
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default(omit) }}"
  roles:
    - role: common
  tags:
    - common

- name: Deploy Mailcow stack
  hosts: home_lab
  become: true
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default(omit) }}"
    ansible_python_interpreter: "{{ hostvars[inventory_hostname].docker_python_interpreter | default(ansible_facts.python.executable | default('/usr/bin/python3')) }}"
  roles:
    - role: mailcow
  tags:
    - mailcow

- name: Deploy PostgreSQL stack
  hosts: home_lab
  become: true
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default(omit) }}"
    ansible_python_interpreter: "{{ hostvars[inventory_hostname].docker_python_interpreter | default(ansible_facts.python.executable | default('/usr/bin/python3')) }}"
  roles:
    - role: postgres
  tags:
    - postgres

- name: Deploy Nextcloud stack
  hosts: home_lab
  become: true
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default(omit) }}"
    ansible_python_interpreter: "{{ hostvars[inventory_hostname].docker_python_interpreter | default(ansible_facts.python.executable | default('/usr/bin/python3')) }}"
  roles:
    - role: nextcloud
  tags:
    - nextcloud

- name: Deploy n8n stack
  hosts: home_lab
  become: true
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default(omit) }}"
    ansible_python_interpreter: "{{ hostvars[inventory_hostname].docker_python_interpreter | default(ansible_facts.python.executable | default('/usr/bin/python3')) }}"
  roles:
    - role: n8n
  tags:
    - n8n

- name: Deploy pgAdmin stack
  hosts: home_lab
  become: true
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default(omit) }}"
    ansible_python_interpreter: "{{ hostvars[inventory_hostname].docker_python_interpreter | default(ansible_facts.python.executable | default('/usr/bin/python3')) }}"
  roles:
    - role: pgadmin
  tags:
    - pgadmin

- name: Deploy Qdrant stack
  hosts: home_lab
  become: true
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default(omit) }}"
    ansible_python_interpreter: "{{ hostvars[inventory_hostname].docker_python_interpreter | default(ansible_facts.python.executable | default('/usr/bin/python3')) }}"
  roles:
    - role: qdrant
  tags:
    - qdrant

- name: Deploy Nginx Proxy Manager stack
  hosts: home_lab
  become: true
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_SSH_KEY_PATH') | default(omit) }}"
    ansible_python_interpreter: "{{ hostvars[inventory_hostname].docker_python_interpreter | default(ansible_facts.python.executable | default('/usr/bin/python3')) }}"
  roles:
    - role: nginx_proxy_manager
  tags:
    - nginx_proxy_manager
