---
- name: Ensure Nextcloud directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - "{{ nextcloud_data_path }}"
    - "{{ nextcloud_data_path }}/app"
    - "{{ nextcloud_data_path }}/db"
  when: nextcloud_state == 'present'

- name: Deploy Nextcloud compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ nextcloud_data_path }}/docker-compose.yml"
    mode: "0644"
  when: nextcloud_state == 'present'

- name: Ensure Nextcloud stack is running
  community.docker.docker_compose:
    project_src: "{{ nextcloud_data_path }}"
    state: present
  when: nextcloud_state == 'present'

- name: Tear down Nextcloud stack when absent
  community.docker.docker_compose:
    project_src: "{{ nextcloud_data_path }}"
    state: absent
  when: nextcloud_state == 'absent'

- name: Remove Nextcloud directory when absent
  ansible.builtin.file:
    path: "{{ nextcloud_data_path }}"
    state: absent
  when: nextcloud_state == 'absent'
