---
n8n_state: present
n8n_project_name: n8n
n8n_data_path: "{{ base_deploy_path }}/n8n"

n8n_compose_defaults:
  project_src: "{{ n8n_data_path }}"
  state: "{{ 'present' if n8n_state == 'present' else 'absent' }}"
  project_name: "{{ n8n_project_name }}"
  pull: true
  recreate: smart
  remove_orphans: true
  build: false

n8n_compose_overrides: {}
n8n_compose: "{{ n8n_compose_defaults | combine(n8n_compose_overrides, recursive=True) }}"
